# .github/workflows/build.yml
name: Build Native Gems
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Windows, Mac(Apple Silicon), Mac(Intel)
        os: [windows-latest, macos-latest, macos-15-intel]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Install Build Tools
        run: gem install rake-compiler mini_portile2

      - name: Compile Extension
        run: rake compile

      - name: Build Gem
        run: gem build nxruby.gemspec

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gem-${{ matrix.os }}
          path: "*.gem"